<?php
declare(strict_types=1);

namespace MediaWiki\Extension\GoogleAdSense;

use Config;
use MediaWiki\Html\Html;

/**
 * HTML rendering for ad containers.
 */
final class AdRenderer
{

	/**
	 * Marker generated by <adsense /> parser tag.
	 * We encode the attributes as JSON in a data attribute to avoid HTML parsing issues.
	 */
	public const INLINE_MARKER_REGEX = '/<span\s+class="mw-googleadsense-marker"\s+data-adsense-attrs="(?P<attrs>[^"]*)"\s*>\s*<\/span>/i';

	public static function renderAdsenseScriptTag(string $client): string
	{
		if ($client === '') {
			return '';
		}
		$includes = 'https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=' . rawurlencode($client);
		return Html::element(
			'script',
			[
				'async' => 'async',
				'includes' => $includes,
				'crossorigin' => 'anonymous',
			],
			''
		);
	}

	/**
	 * Render an ad placement wrapper. Returns empty string if misconfigured.
	 *
	 * @param array $overrides Supported keys: slot, format, responsive, style
	 */
	public static function renderPlacement(Config $config, string $placement, array $overrides = []): string
	{
		$client = (string) $config->get('GoogleAdSenseClient');
		if ($client === '') {
			return '';
		}

		$slots = $config->get('GoogleAdSenseSlots');
		$slot = (string) ($overrides['slot'] ?? (is_array($slots) ? ($slots[$placement] ?? '') : ''));
		if ($slot === '') {
			return '';
		}

		$format = (string) ($overrides['format'] ?? 'auto');
		$responsive = (string) ($overrides['responsive'] ?? 'true');
		$style = (string) ($overrides['style'] ?? 'display:block');

		$ins = Html::element(
			'ins',
			[
				'class' => 'adsbygoogle',
				'style' => $style,
				'data-ad-client' => $client,
				'data-ad-slot' => $slot,
				'data-ad-format' => $format,
				'data-full-width-responsive' => $responsive,
			],
			''
		);

		return Html::rawElement(
			'div',
			[
				'class' => 'mw-googleadsense mw-googleadsense--' . $placement . ' noprint',
				'data-mw-googleadsense-placement' => $placement,
			],
			$ins
		);
	}

	public static function renderFloatingBottom(Config $config): string
	{
		$ad = self::renderPlacement($config, 'floatingBottom', ['style' => 'display:block']);
		if ($ad === '') {
			return '';
		}

		return Html::rawElement(
			'div',
			[
				'id' => 'mw-googleadsense-floating-bottom',
				'class' => 'mw-googleadsense-floating-bottom noprint',
				'aria-hidden' => 'true',
			],
			Html::rawElement(
				'button',
				[
					'type' => 'button',
					'class' => 'mw-googleadsense-close',
					'aria-label' => 'Close',
				],
				'×'
			) . $ad
		);
	}

	public static function renderLinkClickInterstitial(Config $config): string
	{
		$ad = self::renderPlacement($config, 'linkClick', ['style' => 'display:block']);
		if ($ad === '') {
			return '';
		}

		$dialog = Html::rawElement(
			'div',
			[
				'id' => 'mw-googleadsense-interstitial',
				'class' => 'mw-googleadsense-interstitial noprint',
				'aria-hidden' => 'true',
			],
			Html::rawElement(
				'div',
				['class' => 'mw-googleadsense-interstitial__panel'],
				Html::rawElement(
					'div',
					['class' => 'mw-googleadsense-interstitial__header'],
					Html::rawElement('button', [
						'type' => 'button',
						'class' => 'mw-googleadsense-close',
						'aria-label' => 'Close',
					], '×')
				) .
				Html::rawElement(
					'div',
					['class' => 'mw-googleadsense-interstitial__body'],
					$ad
				) .
				Html::rawElement(
					'div',
					['class' => 'mw-googleadsense-interstitial__footer'],
					Html::element('button', [
						'type' => 'button',
						'class' => 'mw-googleadsense-continue',
					], 'Continue')
				)
			)
		);

		return $dialog;
	}

	public static function renderUniversalTemplates(Config $config): string
	{
		// Templates are hidden; JS clones and injects them into skin-specific positions.
		$placements = ['sidebar', 'footer', 'banner', 'afterContent'];
		$chunks = [];

		foreach ($placements as $p) {
			if (!AdDecision::isPlacementEnabled($config, $p)) {
				continue;
			}
			$ad = self::renderPlacement($config, $p);
			if ($ad === '') {
				continue;
			}
			$chunks[] = Html::rawElement(
				'div',
				[
					'class' => 'mw-googleadsense-template',
					'data-placement' => $p,
				],
				$ad
			);
		}

		if (!$chunks) {
			return '';
		}

		return Html::rawElement(
			'div',
			[
				'id' => 'mw-googleadsense-templates',
				'class' => 'mw-googleadsense-templates',
			],
			implode("\n", $chunks)
		);
	}
}
